# Generated by Django 3.2.8 on 2021-11-15 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211115_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto_has_factura',
            old_name='stock',
            new_name='cantidad',
        ),
    ]
