# Generated by Django 3.2.8 on 2021-11-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_stock_producto_has_factura_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='avisos',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.BooleanField(null=True),
        ),
    ]
